<a href="https://colab.research.google.com/github/TesfayeAdugna/Deep-Learning/blob/main/deep_learning_lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import torch

In [64]:
# ReLU activation
class Activation_ReLU:
  # Forward pass
  def forward(self, inputs):
    # Calculate output values from input
    self.output = torch.max(torch.tensor(0.5), inputs)

In [65]:
# Softmax activation
class Activation_Softmax:
  # Forward pass
  def forward(self, inputs):
    # Get unnormalized probabilities
    exp_values = torch.exp(inputs - torch.max(inputs, dim=1, keepdim=True).values)
    # Normalize them for each sample
    probabilities = exp_values / torch.sum(exp_values, dim=1, keepdim=True)
    self.output = probabilities

In [66]:
# Sigmoid activation
class Activation_Sigmoid:
  # Forward pass
  def forward(self, inputs):
    self.output = 1/(1 + torch.exp(-inputs))

In [67]:
class Loss_CategoricalCrossentropy():
  # Forward pass
  def forward(self, y_pred, y_true):
    # complete the code

    log_likelihoods = -torch.sum(y_true * torch.log(y_pred))

    return log_likelihoods

In [68]:
# Accuracy calculation
class AccuracyCalculator:
    def calculate_accuracy(self, y_true, y_pred):
        if len(y_pred.shape) > 1:
            y_pred = torch.argmax(y_pred, dim=1)

        # Compare predicted labels to true labels
        correct_predictions = (y_pred == y_true).float()

        # Calculate accuracy
        accuracy = torch.mean(correct_predictions).item()
        return accuracy

In [74]:
# Sample data
X = torch.rand(10, 4)  # 10 samples, each with 4 features
y_true = torch.randint(0, 4, size=(4,))
X, y_true

(tensor([[0.8271, 0.5755, 0.3993, 0.2289],
         [0.5516, 0.4295, 0.5034, 0.4927],
         [0.2529, 0.7503, 0.1304, 0.3420],
         [0.3403, 0.0449, 0.4137, 0.4990],
         [0.6061, 0.1296, 0.7338, 0.6960],
         [0.2193, 0.5044, 0.8466, 0.6371],
         [0.7307, 0.5409, 0.8867, 0.8701],
         [0.3944, 0.2456, 0.2540, 0.2694],
         [0.9059, 0.5774, 0.7368, 0.4176],
         [0.4645, 0.1372, 0.7907, 0.5357]]),
 tensor([2, 0, 1, 3]))

In [75]:
# ReLU activation
relu_activation = Activation_ReLU()
relu_activation.forward(X)
relu_activation.output

tensor([[0.8271, 0.5755, 0.5000, 0.5000],
        [0.5516, 0.5000, 0.5034, 0.5000],
        [0.5000, 0.7503, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000],
        [0.6061, 0.5000, 0.7338, 0.6960],
        [0.5000, 0.5044, 0.8466, 0.6371],
        [0.7307, 0.5409, 0.8867, 0.8701],
        [0.5000, 0.5000, 0.5000, 0.5000],
        [0.9059, 0.5774, 0.7368, 0.5000],
        [0.5000, 0.5000, 0.7907, 0.5357]])

In [76]:
# Softmax activation
softmax_activation = Activation_Softmax()
softmax_activation.forward(X)
softmax_activation.output

tensor([[0.3357, 0.2610, 0.2188, 0.1845],
        [0.2645, 0.2341, 0.2520, 0.2494],
        [0.2163, 0.3558, 0.1914, 0.2365],
        [0.2505, 0.1864, 0.2696, 0.2936],
        [0.2597, 0.1612, 0.2950, 0.2841],
        [0.1748, 0.2325, 0.3273, 0.2654],
        [0.2412, 0.1995, 0.2820, 0.2773],
        [0.2768, 0.2385, 0.2405, 0.2442],
        [0.3147, 0.2265, 0.2657, 0.1931],
        [0.2392, 0.1724, 0.3315, 0.2569]])

In [77]:
# Sigmoid activation
sigmoid_activation = Activation_Sigmoid()
sigmoid_activation.forward(X)
sigmoid_activation.output

tensor([[0.6957, 0.6400, 0.5985, 0.5570],
        [0.6345, 0.6058, 0.6233, 0.6207],
        [0.5629, 0.6792, 0.5326, 0.5847],
        [0.5843, 0.5112, 0.6020, 0.6222],
        [0.6471, 0.5324, 0.6756, 0.6673],
        [0.5546, 0.6235, 0.6998, 0.6541],
        [0.6750, 0.6320, 0.7082, 0.7048],
        [0.5973, 0.5611, 0.5632, 0.5670],
        [0.7122, 0.6405, 0.6763, 0.6029],
        [0.6141, 0.5342, 0.6880, 0.6308]])

In [78]:
# Categorical Crossentropy loss
categorical_crossentropy_loss = Loss_CategoricalCrossentropy()
loss = categorical_crossentropy_loss.forward(softmax_activation.output, y_true)
loss

tensor(82.8469)

In [79]:
# Categorical Crossentropy loss
categorical_crossentropy_loss = Loss_CategoricalCrossentropy()
loss = categorical_crossentropy_loss.forward(relu_activation.output, y_true)
loss

tensor(32.1297)

In [80]:
# Categorical Crossentropy loss
categorical_crossentropy_loss = Loss_CategoricalCrossentropy()
loss = categorical_crossentropy_loss.forward(sigmoid_activation.output, y_true)
loss

tensor(28.2962)

In [82]:
# Accuracy calculation
accuracy_calculator = AccuracyCalculator()
y_true = torch.randint(0, 4, size=(10,))
accuracy = accuracy_calculator.calculate_accuracy(y_true, softmax_activation.output.argmax(dim=1))
accuracy

0.20000000298023224

In [83]:
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 20.00%
